### ISSUE TITLE
ClassCastException: com.mongodb.BasicDBObject cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-mongo#105]
Error may very well be legitimate, but this is a bad error message that does not indicate what is actually wrong.

```
2015-04-28 15:37:56,687 [hystrix-UpdateEntityInfoCommand-1] ERROR [com.redhat.lightblue.metadata.parser.MetadataParser] com.mongodb.BasicDBObject cannot be cast to java.lang.String: java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to java.lang.String
	at com.redhat.lightblue.metadata.mongo.BSONParser.getProjection(BSONParser.java:249)
	at com.redhat.lightblue.metadata.mongo.BSONParser.getProjection(BSONParser.java:53)
	at com.redhat.lightblue.metadata.parser.MetadataParser.parseReferenceField(MetadataParser.java:797)
	at com.redhat.lightblue.metadata.parser.MetadataParser.parseField(MetadataParser.java:755)
	at com.redhat.lightblue.metadata.parser.MetadataParser.parseFields(MetadataParser.java:691)
	at com.redhat.lightblue.metadata.parser.MetadataParser.parseEntitySchema(MetadataParser.java:453)
	at com.redhat.lightblue.metadata.mongo.MongoMetadata.validateAllVersions(MongoMetadata.java:382)
	at com.redhat.lightblue.metadata.mongo.MongoMetadata.updateEntityInfo(MongoMetadata.java:331)
	at com.redhat.lightblue.rest.metadata.hystrix.UpdateEntityInfoCommand.run(UpdateEntityInfoCommand.java:61)
	at com.redhat.lightblue.rest.metadata.hystrix.UpdateEntityInfoCommand.run(UpdateEntityInfoCommand.java:33)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dcrissman** [comment]
The returned object in this case would appear to be null, which indicates that no projection was provided. Is it valid that no projection would be provided?

And since I am looking at this, the comparable getQuery and getSort methods to the exact same thing. So is it valid that either of these could be not provided either?

**Comment by dcrissman** [comment]
@bserdar any chance you could weigh in on this one?

**Comment by bserdar** [comment]
I will look tonight

**Comment by bserdar** [comment]
Is this by any chance an old metadata? At some point, we changed
projections/queries/sorts to be represented as strings instead of Json
objects. It looks like this metadata has them as objects, not strings.

**Comment by dcrissman** [comment]
I am attempting to update the entityInfo on an existing entity. I am new to this particular entity, so it is possible what you suggest is true. My upload contains only the entityInfo, no schema. Might this error be from an existing schema version?

**Comment by bserdar** [comment]
Possible. It won't be able to load that entity if that's the case. If you
have mongodb access, you can fix it manually, or delete the entity and
recreate it.

**Comment by dcrissman** [comment]
Was able to manually fix
