### ISSUE TITLE
Failing unit test

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-mongo#98]
MongoCRUDControllerTest.insertTest_empty_array
```
java.lang.AssertionError: empty array was not inserted
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at com.redhat.lightblue.crud.mongo.MongoCRUDControllerTest.insertTest_empty_array(MongoCRUDControllerTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by bserdar** [comment]
I'll take a look at this one.

**Comment by bserdar** [comment]
I think this is because of the new semantics of projecting container fields
like this. I'll skip this test for now, and open an issue for it.

**Comment by bserdar** [comment]
The document inserted is:

{
  "objectType":"test",
  "field7": [ ]
 }

But when it is projected, the empty array field is not returned back. The projection is excluding it, because there is nothing under field7. We need to decide if this is acceptable behavior, or whether we should change how projector behaves.

**Comment by dcrissman** [comment]
I don't see a reason why if someone inserts an empty array and then they want it projected back, that they shouldn't get it.

**Comment by bserdar** [comment]
The way projection works now is that an array or object is projected once
something under it is projected. That means, if it is empty, it doesn't
even show up.

**Comment by dcrissman** [comment]
@jewzaam @luan-cestari @paterczm @derek63 Any thoughts?

**Comment by jewzaam** [comment]
Fields without data are not returned even if projected.
In this case, the field has data: an empty array.

By that reasoning I say we should return it.

**Comment by dcrissman** [comment]
This bug is blocking https://github.com/lightblue-platform/lightblue-core/issues/376 as we cannot creates builds.

**Comment by dcrissman** [comment]
@bserdar created a work around, so https://github.com/lightblue-platform/lightblue-core/issues/376 is no longer blocked.
